In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]
b = [[20, 25, 27],[29, 33, 40]]

In [3]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [4]:
np.exp(b)

array([[4.85165195e+08, 7.20048993e+10, 5.32048241e+11],
       [3.93133430e+12, 2.14643580e+14, 2.35385267e+17]])

In [5]:
np.sum(np.exp(b))

2.356044462894082e+17

In [6]:
np.sum(np.exp(a))

30.19287485057736

In [7]:
a/np.sum(np.exp(a))

array([0.0331204 , 0.06624079, 0.09936119])

In [10]:
2*np.array(b)

array([[40, 50, 54],
       [58, 66, 80]])